network/gajim: Support 1.0.x series.
Signed-off-by: Andrew Clemons <andrew.clemons@gmail.com>

diff --git a/network/gajim/gajim.SlackBuild b/network/gajim/gajim.SlackBuild
--- a/network/gajim/gajim.SlackBuild
+++ b/network/gajim/gajim.SlackBuild
@@ -60,10 +60,22 @@ set -e
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
-rm -rf $PRGNAM-$VERSION
-tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
-cd $PRGNAM-$VERSION
-patch -p1 < $CWD/narrow_python.diff
+rm -rf $PRGNAM-$VERSION $PRGNAM-$PRGNAM-$VERSION
+if [ -e $CWD/$PRGNAM-$VERSION.tar.bz2 ] ; then
+  tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
+  cd $PRGNAM-$VERSION
+elif [ -e $CWD/$PRGNAM-$PRGNAM-$VERSION.tar.bz2 ] ; then
+  tar xvf $CWD/$PRGNAM-$PRGNAM-$VERSION.tar.bz2
+  cd $PRGNAM-$PRGNAM-$VERSION
+else
+  echo "File not found"
+  exit 1
+fi
+
+if [ "$(echo "$VERSION" | cut -d. -f1)" =  "0" ] ; then
+  patch -p1 < $CWD/narrow_python.diff
+fi
+
 chown -R root:root .
 find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
@@ -71,22 +83,31 @@ find -L . \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
   -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-CFLAGS="$SLKCFLAGS" \
-CXXFLAGS="$SLKCFLAGS" \
-./configure \
-  --prefix=/usr \
-  --libdir=/usr/lib${LIBDIRSUFFIX} \
-  --sysconfdir=/etc \
-  --localstatedir=/var \
-  --mandir=/usr/man \
-  --docdir=/usr/doc/$PRGNAM-$VERSION \
-  --build=$ARCH-slackware-linux
+if [ -e configure ] ; then
+  CFLAGS="$SLKCFLAGS" \
+  CXXFLAGS="$SLKCFLAGS" \
+  ./configure \
+    --prefix=/usr \
+    --libdir=/usr/lib${LIBDIRSUFFIX} \
+    --sysconfdir=/etc \
+    --localstatedir=/var \
+    --mandir=/usr/man \
+    --docdir=/usr/doc/$PRGNAM-$VERSION \
+    --build=$ARCH-slackware-linux
 
-make
-make install DESTDIR=$PKG
+  make
+  make install DESTDIR=$PKG
+else
+  python3 setup.py install --root=$PKG
+fi
+
 
 find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
+
+if [ -e $PKG/usr/share/man ] ; then
+  mv $PKG/usr/share/man $PKG/usr/
+fi
 
 find $PKG/usr/man -type f -exec gzip -9 {} \;
 for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
